# To boot the app run the following:
# docker-compose run auto-gpt
version: "3.9"

services:
  auto-gpt:
    image: python-3.10:v2
    build: ./
    env_file: .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/www/autogpt:/home/appuser/autogpt:rw
    command: sh /home/appuser/autogpt/autogptapi/run.sh
    container_name: auto-gpt